<?php

return [
    'users' => [
        [
            'name' => 'Alessandra',
            'surname' => 'Ferrari',
            'email' => 'alessandra.ferrari@example.com',
            'password' => 'sicuro1234',
        ],
        [
            'name' => 'Beatrice',
            'surname' => 'Ricci',
            'email' => 'beatrice.ricci@example.com',
            'password' => 'firenze2024',
        ],
        [
            'name' => 'Carlo',
            'surname' => 'Esposito',
            'email' => 'carlo.esposito@example.com',
            'password' => 'barisicura',
        ],
        [
            'name' => 'Daniele',
            'surname' => 'Conti',
            'email' => 'daniele.conti@example.com',
            'password' => 'contidani',
        ],
        [
            'name' => 'Emanuela',
            'surname' => 'Marino',
            'email' => 'emanuela.marino@example.com',
            'password' => 'sardegnalibera',
        ],
        [
            'name' => 'Francesco',
            'surname' => 'Greco',
            'email' => 'francesco.greco@example.com',
            'password' => 'genova2024',
        ],
        [
            'name' => 'Giovanni',
            'surname' => 'Mancini',
            'email' => 'giovanni.mancini@example.com',
            'password' => 'torino123',
        ],
        [
            'name' => 'Ilaria',
            'surname' => 'Costa',
            'email' => 'ilaria.costa@example.com',
            'password' => 'verona2024',
        ],
        [
            'name' => 'Chiara',
            'surname' => 'Barbieri',
            'email' => 'chiara.barbieri@example.com',
            'password' => 'bolognasicura',
        ],
        [
            'name' => 'Mario',
            'surname' => 'Fontana',
            'email' => 'mario.fontana@example.com',
            'password' => 'romaeterna',
        ],
    ],

    'accounts' => [
        [
            'image' => 'storage/images/doc-1.jpg',
            'cv' => '',
            'phone' => '3471234567',
            'address' => 'Via Napoli 100',
            'performances' => '',
            'visible' => 1,
        ],
        [
            'image' => 'storage/images/doc-2.jpg',
            'cv' => '',
            'phone' => '3397654321',
            'address' => 'Piazza del Mercato 22',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-3.jpg',
            'cv' => '',
            'phone' => '3456789012',
            'address' => 'Via Lazio 5',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-4.jpg',
            'cv' => '',
            'phone' => '3339876543',
            'address' => 'Corso Umberto I, 27',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-5.jpg',
            'cv' => '',
            'phone' => '3287654321',
            'address' => 'Viale Regina Margherita 8',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-6.jpg',
            'cv' => '',
            'phone' => '3401234567',
            'address' => 'Via Garibaldi 54',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-7.jpg',
            'cv' => '',
            'phone' => '3478901234',
            'address' => 'Piazza San Carlo 33',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-8.jpg',
            'cv' => '',
            'phone' => '3498765432',
            'address' => 'Via dei Mille 21',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-9.jpg',
            'cv' => '',
            'phone' => '3334567890',
            'address' => 'Via XX Settembre 12',
            'performances' => '',
            'visible' => 0,
        ],
        [
            'image' => 'storage/images/doc-10.jpg',
            'cv' => '',
            'phone' => '3281234567',
            'address' => 'Corso Vittorio Emanuele II, 58',
            'performances' => '',
            'visible' => 0,
        ],
    ],

    'specializations' => [
        [
            'name' => 'Odontoiatria',
        ],
        [
            'name' => 'Cardiologia',
        ],
        [
            'name' => 'Dermatologia',
        ],
        [
            'name' => 'Neurologia',
        ],
        [
            'name' => 'Pediatria',
        ],
        [
            'name' => 'Ortopedia',
        ],
        [
            'name' => 'Ginecologia',
        ],
    ],

    'sponsorships' => [
        [
            'name' => 'Giornaliero',
            'duration' => '24:00:00',
            'price' => '2.99',
            'image' => '',
        ],
        [
            'name' => 'Tre Giorni',
            'duration' => '72:00:00',
            'price' => '5.99',
            'image' => '',
        ],
        [
            'name' => 'Sei Giorni',
            'duration' => '144:00:00',
            'price' => '9.99',
            'image' => '',
        ],
    ],

    'ratings' => [
        [
            'value' => 1,
        ],
        [
            'value' => 2,
        ],
        [
            'value' => 3,
        ],
        [
            'value' => 4,
        ],
        [
            'value' => 5,
        ],
    ],

    'account_rating' => [
        [
            'account_id' => 1,
            'rating_id' => 1,
        ],
        [
            'account_id' => 2,
            'rating_id' => 3,
        ],
        [
            'account_id' => 3,
            'rating_id' => 5,
        ],
        [
            'account_id' => 4,
            'rating_id' => 5,
        ],
        [
            'account_id' => 5,
            'rating_id' => 1,
        ],
        ['account_id' => 4, 'rating_id' => 5],
        ['account_id' => 4, 'rating_id' => 5],
        ['account_id' => 10, 'rating_id' => 4],
        ['account_id' => 4, 'rating_id' => 5],
        ['account_id' => 10, 'rating_id' => 3],
        ['account_id' => 4, 'rating_id' => 5],
        ['account_id' => 1, 'rating_id' => 5],
        ['account_id' => 8, 'rating_id' => 4],
        ['account_id' => 3, 'rating_id' => 5],
        ['account_id' => 6, 'rating_id' => 5],
        ['account_id' => 2, 'rating_id' => 5],
        ['account_id' => 6, 'rating_id' => 5],
        ['account_id' => 9, 'rating_id' => 1],
        ['account_id' => 1, 'rating_id' => 1],
        ['account_id' => 9, 'rating_id' => 4],
        ['account_id' => 5, 'rating_id' => 1],
        ['account_id' => 2, 'rating_id' => 5],
        ['account_id' => 5, 'rating_id' => 1],
        ['account_id' => 7, 'rating_id' => 4],
        ['account_id' => 8, 'rating_id' => 5],
        ['account_id' => 8, 'rating_id' => 4],
        ['account_id' => 3, 'rating_id' => 5],
        ['account_id' => 6, 'rating_id' => 3],
        ['account_id' => 3, 'rating_id' => 5],
        ['account_id' => 5, 'rating_id' => 3],
        ['account_id' => 5, 'rating_id' => 1],
        ['account_id' => 9, 'rating_id' => 5],
        ['account_id' => 3, 'rating_id' => 5],
        ['account_id' => 6, 'rating_id' => 3],
        ['account_id' => 6, 'rating_id' => 4],
        ['account_id' => 7, 'rating_id' => 4],
        ['account_id' => 10, 'rating_id' => 3],
        ['account_id' => 6, 'rating_id' => 3],
        ['account_id' => 4, 'rating_id' => 4],
        ['account_id' => 1, 'rating_id' => 1],
        ['account_id' => 3, 'rating_id' => 3],
        ['account_id' => 6, 'rating_id' => 5],
        ['account_id' => 8, 'rating_id' => 1],
    ],

    'account_specialization' => [
        ['account_id' => 1, 'specialization_id' => 1],
        ['account_id' => 2, 'specialization_id' => 3],
        ['account_id' => 3, 'specialization_id' => 5],
        ['account_id' => 4, 'specialization_id' => 2],
        ['account_id' => 5, 'specialization_id' => 1],
        ['account_id' => 6, 'specialization_id' => 2],
        ['account_id' => 8, 'specialization_id' => 5],
        ['account_id' => 10, 'specialization_id' => 5],
        ['account_id' => 8, 'specialization_id' => 4],
        ['account_id' => 10, 'specialization_id' => 7],
        ['account_id' => 6, 'specialization_id' => 4],
        ['account_id' => 4, 'specialization_id' => 7],
        ['account_id' => 7, 'specialization_id' => 2],
        ['account_id' => 5, 'specialization_id' => 2],
        ['account_id' => 3, 'specialization_id' => 1],
        ['account_id' => 9, 'specialization_id' => 5],
        ['account_id' => 7, 'specialization_id' => 1]
    ],

    'account_sponsorship' => [
        [
            'account_id' => 1,
            'sponsorship_id' => 3,
        ],
        [
            'account_id' => 2,
            'sponsorship_id' => 3,
        ],
        [
            'account_id' => 3,
            'sponsorship_id' => 3,
        ],
        [
            'account_id' => 4,
            'sponsorship_id' => 3,
        ],
    ],

    'messages' => [
        [
            'account_id' => 5,
            'name' => 'Mario Rossi',
            'content' => 'Vorrei prenotare una visita per domani',
            'title' => 'Visita Urgente',
            'email' => 'mariorossi@example.com',
        ],
        [
            'account_id' => 4,
            'name' => 'Enzo Bianchi',
            'content' => 'Il mio problema mi si è ripresentato',
            'title' => 'Problema al colon',
            'email' => 'enzo@example.com',
        ],
        [
            'account_id' => 2,
            'name' => 'Giovanna Rossi',
            'content' => 'Vorrei prenotare una visita il prima possibile',
            'title' => 'Visita di controllo',
            'email' => 'gi@example.com',
        ],
        [
            'account_id' => 6,
            'name' => 'Andrea Bruno',
            'content' => 'Vorrei prenotare una visita il prima possibile',
            'title' => 'Visita Funzionale',
            'email' => 'mariorossi@example.com',
        ],
        [
            'account_id' => 9,
            'name' => 'Alessandro Rossi',
            'content' => 'Mi serve un certificato medico per i prossimi 3 giorni ',
            'title' => 'Certificato Medico',
            'email' => 'alessandrolessandro@example.com',
        ],
    ],

    'reviews' => [
        [
            'name' => 'Sophia Salvemini',
            'title' => ' Competenza e Attese',
            'email' => 'telemaco99@tim.it',
            'content' => 'molto competente e premuroso nel suo lavoro. Tuttavia, spesso ho dovuto aspettare più del previsto per il mio turno',
            'account_id' => 3,
        ],
        ['name' => 'Ludovica Canova', 'title' => 'Competenza vs Disponibilità', 'email' => 'martina18@pasqua-travaglio.it', 'content' => 'estremamente gentile e paziente, ma talvolta la sua disponibilità per appuntamenti last-minute è limitata.', 'account_id' => 7],
        ['name' => 'Sig.ra Emma Donatoni', 'title' => 'Professione e Cortesia', 'email' => 'stoppaniornella@virgilio.it', 'content' => 'molto professionale e preciso nelle sue diagnosi,  il suo staff è cordiale e accogliente.', 'account_id' => 2],
        ['name' => 'Piermaria Giannuzzi', 'title' => 'Un Mix di Esperienze', 'email' => 'burcardodonatello@farina-russo.com', 'content' => 'Ho ricevuto un trattamento eccezionale ma il parcheggio presso il suo studio è sempre un incubo."', 'account_id' => 6],
        ['name' => 'Liana Pizziol-Farina', 'title' => 'Meticolosità e Tempi di Attesa', 'email' => 'benedettofranceschi@sobrero.com', 'content' => 'molto attenta e meticolosa, ma ho avuto alcuni problemi con la puntualità delle sue visite.', 'account_id' => 9],
        ['name' => 'Roberta Travaglio-Semitecolo', 'title' => '"Efficienza Medica vs Organizzazione', 'email' => 'marco23@lollobrigida-conte.it', 'content' => 'ha risolto i miei problemi di salute in modo efficace', 'account_id' => 7],
        ['name' => 'Enzio Gaito', 'title' => 'Soddisfazione e Disponibilità', 'email' => 'luciamartinelli@tin.it', 'content' => 'Sono rimasto molto soddisfatto del trattamento ricevuto anche se a volte è difficile ottenere un appuntamento con lei.', 'account_id' => 5],
        ['name' => 'Gianluigi Morandi-Nordio', 'title' => 'Professione e Pazienza', 'email' => 'jsquarcione@piazzi.it', 'content' => 'molto brava nel suo campo', 'account_id' => 9],
        ['name' => 'Sig.ra Licia Turchetta', 'title' => 'Competenza vs Comfort', 'email' => 'dborgia@yahoo.com', 'content' => 'molto gentile e ben informata, ma il suo studio potrebbe essere più moderno e accogliente.', 'account_id' => 1],
        ['name' => 'Coluccio Savorgnan', 'title' => '"Chiarezza e Accessibilità', 'email' => 'vianellotemistocle@dallape.com', 'content' => 'Ho avuto una buona esperienza  ma a volte le sue spiegazioni possono essere un po\' confuse.', 'account_id' => 5],
        ['name' => 'Diana Fusani', 'title' => 'Empatia e Flessibilità', 'email' => 'venanciomodigliani@vodafone.it', 'content' => 'molto disponibile e competente, ma vorrei che avesse più flessibilità negli orari degli appuntamenti.', 'account_id' => 4],
        ['name' => 'Ottavio Mazzini', 'title' => 'Professionismo Incrollabile', 'email' => 'ettorecheda@libero.it', 'content' => 'estremamente professionale,  la sua segreteria è molto efficiente nella gestione delle chiamate.', 'account_id' => 7],
        ['name' => 'Nadia Tanzini', 'title' => 'Puntualità e Pazienza', 'email' => 'gianluigicrespi@calvo.net', 'content' => 'molto attenta alle esigenze dei pazienti,', 'account_id' => 2],
        ['name' => 'Fabio Delle-Vergassola', 'title' => 'Eccellenza e Distanza', 'email' => 'antonelloforza@rinaldi.com', 'content' => 'Ho ricevuto un trattamento eccellente  ma il suo studio è un po\' fuori mano per me.', 'account_id' => 7],
        ['name' => 'Vittorio Leopardi', 'title' => 'Coordinazione e Comunicazione', 'email' => 'giuseppina14@marinetti.it', 'content' => 'molto brava nel suo lavoro, non ho avuto difficoltà a comunicare con il suo staff.', 'account_id' => 5],
        ['name' => 'Tina Falloppio', 'title' => 'Competenza e Gestione del Tempo', 'email' => 'mauro37@libero.it', 'content' => ' molto professionale e competente, ma il suo studio potrebbe beneficiare di una migliore gestione del tempo.', 'account_id' => 10],
        ['name' => 'Osvaldo Rusticucci', 'title' => 'Soddisfazione e Organizzazione', 'email' => 'tcasini@badoglio-iannucci.it', 'content' => 'Sono rimasto soddisfatto del trattamento ricevuto  la sua segreteria è molto organizzata.', 'account_id' => 6],
        ['name' => 'Antonia Filippelli', 'title' => 'Professionismo vs Orari', 'email' => 'valentina24@libero.it', 'content' => 'molto disponibile e gentile, ma i suoi orari di apertura potrebbero essere più convenienti.', 'account_id' => 10],
        ['name' => 'Sonia Ruffini', 'title' => '"Esperienza Positiva ', 'email' => 'omascagni@gmail.com', 'content' => 'Ho avuto una buona esperienza ', 'account_id' => 3],
        ['name' => 'Piergiuseppe Tropea', 'title' => 'Esperienza Equilibrata', 'email' => 'borsieretorquato@cremonesi-verga.net', 'content' => 'molto professionale, ma il parcheggio presso il suo studio è sempre pieno.', 'account_id' => 4],
        ['name' => 'Jacopo Cafarchia-Michelangeli', 'title' => 'Non molto efficiente', 'email' => 'xtrezzini@virgilio.it', 'content' => 'Vorrei avesse più tempo da dedicare ad ogni singolo paziente.', 'account_id' => 8],
        ['name' => 'Cirillo Lanfranchi', 'title' => 'Ufficio caotico', 'email' => 'jlopresti@curatoli.it', 'content' => 'Ufficio sempre caotico', 'account_id' => 9],
        ['name' => 'Giada Rienzo', 'title' => '"Caos e Competenza', 'email' => 'ortolanifortunata@gmail.com', 'content' => 'molto bravo nel suo lavoro, ma a volte ho avuto difficoltà a capire il suo piano di trattamento.', 'account_id' => 6],
        ['name' => 'Fabrizia Squarcione-Cantimori', 'title' => 'Attenzione e Gestione', 'email' => 'ramona50@ferrabosco.it', 'content' => 'molto attenta e competente, ma la sua segreteria potrebbe essere più efficiente nella gestione degli appuntamenti.', 'account_id' => 1],
        ['name' => 'Ezio Righi', 'title' => 'Gentilezza e Disponibilità', 'email' => 'giampaoloangeli@giannini-venturi.it', 'content' => 'molto gentile e premurosa un vero dottore', 'account_id' => 1],
        ['name' => 'Angelina Pucci', 'title' => 'Dettaglio e Chiarezza', 'email' => 'afantoni@gmail.com', 'content' => 'Ho ricevuto un trattamento eccellente  anche se a volte le sue spiegazioni sono state un po\' complesse.', 'account_id' => 8],
        ['name' => 'Giancarlo Badoer', 'title' => 'Professionismo e Pianificazione', 'email' => 'isa65@tiscali.it', 'content' => 'molto professionale', 'account_id' => 4],
        ['name' => 'Bianca Barberini', 'title' => '"Esperienza Soddisfacente ma...', 'email' => 'bmanacorda@babbo-inzaghi.org', 'content' => 'Rimasto molto soddisfatto del trattamento ma molto costoso', 'account_id' => 5],
        ['name' => 'Federica Cipolla-Tosi', 'title' => 'Accessibilità e Competenza', 'email' => 'giulio70@gmail.com', 'content' => 'molto competente, ma il suo studio potrebbe essere più accessibile per i pazienti con disabilità.', 'account_id' => 9],
        ['name' => 'Osvaldo Giannetti', 'title' => '"Chiarezza e Comprensione', 'email' => 'vgiorgetti@manunta.org', 'content' => 'Molto brava nel suo lavoro e anche nella spiegazione del piano di trattamento', 'account_id' => 9],
    ],
];
